# Generated by Django 5.1.5 on 2026-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NepseAnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('indicator', models.CharField(choices=[('sma_20', 'SMA 20'), ('sma_50', 'SMA 50'), ('sma_200', 'SMA 200'), ('rsi_14', 'RSI 14'), ('volatility_30', 'Volatility 30-day'), ('daily_return', 'Daily Return'), ('cumulative_return', 'Cumulative Return')], max_length=30)),
                ('value', models.DecimalField(decimal_places=6, max_digits=16)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Cache',
                'verbose_name_plural': 'Analytics Cache',
                'ordering': ['-date'],
                'unique_together': {('date', 'indicator')},
            },
        ),
        migrations.CreateModel(
            name='NepseIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, default='NEPSE', help_text='Index or stock symbol (e.g. NEPSE)', max_length=20)),
                ('date', models.DateField(db_index=True, help_text='Trading date', unique=True)),
                ('open_price', models.DecimalField(decimal_places=2, help_text='Opening price', max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, help_text='Highest price of the day', max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, help_text='Lowest price of the day', max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, help_text='Closing price', max_digits=12)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=4, help_text='Daily percent change', max_digits=8, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Trading volume (turnover in NPR)', max_digits=20, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='When this record was imported')),
            ],
            options={
                'verbose_name': 'NEPSE Index Data',
                'verbose_name_plural': 'NEPSE Index Data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='nepse_nepse_symbol_2f2f05_idx'), models.Index(fields=['date', 'close_price'], name='nepse_nepse_date_fbbedf_idx')],
            },
        ),
    ]
