# Generated by Django 5.1.5 on 2026-04-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nepse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NepseAnalyticsCache',
        ),
    ]
