# Generated by Django 5.1.5 on 2026-04-18 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('report_type', models.CharField(choices=[('portfolio_summary', 'Portfolio Summary'), ('nepse_analysis', 'NEPSE Market Analysis'), ('goal_progress', 'Goal Progress Report'), ('health_assessment', 'Financial Health Assessment'), ('monthly_review', 'Monthly Investment Review')], max_length=30)),
                ('content', models.JSONField(default=dict, help_text='Structured report content as JSON')),
                ('summary', models.TextField(blank=True, help_text='AI-generated executive summary')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
