# Generated by Django 5.1.5 on 2026-04-18 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Goal name (e.g. 'Buy a house')", max_length=200)),
                ('category', models.CharField(choices=[('retirement', 'Retirement'), ('education', 'Education Fund'), ('home', 'Home Purchase'), ('emergency', 'Emergency Fund'), ('wealth', 'Wealth Building'), ('business', 'Business Investment'), ('travel', 'Travel Fund'), ('other', 'Other')], default='wealth', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target amount in NPR', max_digits=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, help_text='Current amount saved towards goal', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, help_text='Planned monthly contribution in NPR', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_return_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Expected annual return rate (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),
                ('target_date', models.DateField(help_text='Target date to achieve the goal')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this goal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Goal',
                'verbose_name_plural': 'Investment Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('contributed_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='planner.investmentgoal')),
            ],
            options={
                'verbose_name': 'Goal Contribution',
                'verbose_name_plural': 'Goal Contributions',
                'ordering': ['-contributed_at'],
            },
        ),
    ]
