# Generated by Django 5.1.5 on 2026-04-18 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(help_text='Overall financial health (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('diversification_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('goal_progress_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('savings_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('investment_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('insights', models.JSONField(default=list, help_text='List of AI-generated insight strings')),
                ('recommendations', models.JSONField(default=list, help_text='List of recommended actions')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Score',
                'verbose_name_plural': 'Health Scores',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Portfolio', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Asset name (e.g. 'NABIL Bank Stocks')", max_length=200)),
                ('asset_type', models.CharField(choices=[('stocks', 'Stocks'), ('bonds', 'Government Bonds'), ('mutual_fund', 'Mutual Funds'), ('fixed_deposit', 'Fixed Deposits'), ('gold', 'Gold'), ('real_estate', 'Real Estate'), ('crypto', 'Cryptocurrency'), ('savings', 'Savings Account'), ('other', 'Other')], max_length=20)),
                ('invested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_allocation', models.DecimalField(decimal_places=2, default=0, help_text='Target allocation percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Asset',
                'verbose_name_plural': 'Portfolio Assets',
                'ordering': ['-current_value'],
            },
        ),
        migrations.CreateModel(
            name='RebalancingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Suggested rebalance amount in NPR', max_digits=15)),
                ('current_allocation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_allocation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(help_text='AI-generated reasoning for this action')),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('executed', 'Executed')], default='recommended', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalancing_logs', to='portfolio.portfolioasset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebalancing_logs', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Rebalancing Log',
                'verbose_name_plural': 'Rebalancing Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
